IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID('[dbo].[TabMotor_Asignacion_TMC_elim]') AND type = 'U')
CREATE TABLE [dbo].[TabMotor_Asignacion_TMC_elim]
(
    [id_Asign] int NOT NULL,
    [Periodo] varchar(6) COLLATE Modern_Spanish_CI_AS NULL,
    [Afiliado_Rut] decimal(10, 0) NULL,
    [Afiliado_Dv] varchar(1) COLLATE Modern_Spanish_CI_AS NOT NULL,
    [Nombre] varchar(max) COLLATE Modern_Spanish_CI_AS NULL,
    [Apellido] varchar(max) COLLATE Modern_Spanish_CI_AS NULL,
    [Empresa_Rut] varchar(255) COLLATE Modern_Spanish_CI_AS NOT NULL,
    [Empresa_Dv] varchar(1) COLLATE Modern_Spanish_CI_AS NOT NULL,
    [Empresa] varchar(255) COLLATE Modern_Spanish_CI_AS NOT NULL,
    [ClaRiesgoEmpresa] varchar(20) COLLATE Modern_Spanish_CI_AS NOT NULL,
    [Holding] varchar(25) COLLATE Modern_Spanish_CI_AS NOT NULL,
    [Celular] varchar(15) COLLATE Modern_Spanish_CI_AS NOT NULL,
    [Telefono1] varchar(15) COLLATE Modern_Spanish_CI_AS NOT NULL,
    [Telefono2] varchar(15) COLLATE Modern_Spanish_CI_AS NOT NULL,
    [Email] varchar(500) COLLATE Modern_Spanish_CI_AS NOT NULL,
    [MontoPension] decimal(8, 0) NOT NULL,
    [MontoRenta] int NOT NULL,
    [Monto_preaprobado] int NOT NULL,
    [Antiguedad_en_Meses] int NOT NULL,
    [LicMedicaVigente] int NOT NULL,
    [CreditosVigentes] int NOT NULL,
    [CredVig_Meses_Morosos] int NOT NULL,
    [CredVig_MontoCuota] int NOT NULL,
    [EsPensionado] int NOT NULL,
    [EsPrivado] int NOT NULL,
    [EsPublico] int NOT NULL,
    [Contacto] int NOT NULL,
    [Segmento] varchar(11) COLLATE Modern_Spanish_CI_AS NULL,
    [FechaNacimiento] date NULL,
    [Edad] int NOT NULL,
    [PensionadoFFAA] int NOT NULL,
    [EmpresaEsPensionado] int NOT NULL,
    [EmpresaEsPublico] int NOT NULL,
    [EmpresaEsPrivado] int NOT NULL,
    [RiesgoPerfil] varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
    [RiesgoMaxVecesRenta] bigint NULL,
    [RiesgoMaxPreAprobado] bigint NULL,
    [PreAprobadoFinal] bigint NULL,
    [CredVigente] int NOT NULL,
    [Oficina] int NOT NULL,
    [Asignado] int NOT NULL,
    [Ejec_Asignacion] varchar(15) COLLATE Modern_Spanish_CI_AS NULL,
    [TipoAsignacion] int NULL,
    [Prioridad] int NULL,
    [TipoCampania] varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
    [Cuadrante] int NULL,
    [OfertaTexto] varchar(200) COLLATE Modern_Spanish_CI_AS NULL,
)