IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID('[dbo].[TabEncuesta_01_PatologiaMedicamento]') AND type = 'U')
CREATE TABLE [dbo].[TabEncuesta_01_PatologiaMedicamento]
(
    [Id_encuesta] int NOT NULL IDENTITY(1, 1),
    [Rut_Afiliado] varchar(12) COLLATE Modern_Spanish_CI_AS NOT NULL,
    [Nombre_Afiliado] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [Fecha_Encuesta] datetime NOT NULL,
    [Rut_Ejecutivo] varchar(12) COLLATE Modern_Spanish_CI_AS NOT NULL,
    [Sucursal] int NOT NULL,
    [Tiene_Enfermedad] varchar(10) COLLATE Modern_Spanish_CI_AS NOT NULL,
    [Enfermedad_1] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [Enfermedad_2] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [Enfermedad_3] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [Enfermedad_4] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [Enfermedad_5] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [Enfermedad_6] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [Enfermedad_7] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [Enfermedad_8] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [Enfermedad_9] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [Enfermedad_10] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [Enfermedad_11] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [Medicamentos_1] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [Medicamentos_2] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [Medicamentos_3] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [Medicamentos_4] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [Medicamentos_5] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [Medicamentos_6] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [Medicamentos_7] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [Medicamentos_8] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [Medicamentos_9] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [Medicamentos_10] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [Medicamentos_11] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [Medicamentos_12] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [Medicamentos_13] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [Medicamentos_14] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [Medicamentos_15] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [Medicamentos_16] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [Adquiere_Consultorio] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [Adquiere_CanastaGes] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [Adquiere_Farmacia] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [NombreFarmacia] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [Actividad] varchar(150) COLLATE Modern_Spanish_CI_AS NULL,
    [Sexo] varchar(10) COLLATE Modern_Spanish_CI_AS NULL,
    [Edad] varchar(10) COLLATE Modern_Spanish_CI_AS NULL,
    [Prevision] varchar(30) COLLATE Modern_Spanish_CI_AS NULL,
    [Region] varchar(80) COLLATE Modern_Spanish_CI_AS NULL,
    [Flag_Encuesta] int NULL,
    CONSTRAINT [PK_TabEncuesta_01PatologiaMedicamento_ID] PRIMARY KEY CLUSTERED ([Id_encuesta] ASC)
)