IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID('[carteras].[spMotorCartera_Guarda_CabeceraEntrevista]') AND type = 'P')
DROP PROCEDURE [carteras].[spMotorCartera_Guarda_CabeceraEntrevista]
GO
CREATE PROCEDURE [carteras].[spMotorCartera_Guarda_CabeceraEntrevista] --'d52cde23-2278-48a5-adfa-42b42f892d73', '61502000-1','16/10/2018', 'Manuel Vega', 'Empresa', 'Jefe', 'Comnetarios de prueba 2'
@TOKEN VARCHAR(250)
,@RUT_EMPRESA VARCHAR(15)
,@FECHA_ENTREVISTA VARCHAR(100)
,@CONTACTO VARCHAR(200)
,@ESTAMENTO VARCHAR(200)
,@CARGO VARCHAR(200)
,@COMENTARIO VARCHAR(MAX)
,@TELEFONO VARCHAR(200)
,@CORREO VARCHAR(250)
,@ANEXO INT
AS
BEGIN 
DECLARE @RUT_EJECUTIVO_INGRESO VARCHAR(15) = CONVERT(VARCHAR, security.fnSca_ObtenerRutByToken (@TOKEN))
DECLARE @OFICINA_EJECUTIVO_INGRESO INT = CONVERT(INT, security.fnSca_ObtenerOficinaByToken (@TOKEN))


IF  @ANEXO = 0
	BEGIN
		select @ANEXO = IdEmpresaAnexo
		from carteras.TabCart_AnexoEmpresa
		where RutEmpresa = @RUT_EMPRESA and EsMatriz = 1
		and codOficina = @OFICINA_EJECUTIVO_INGRESO
	END


	INSERT INTO [CARTERAS].[TABCART_CABECERAENTREVISTA] 
	VALUES (@RUT_EMPRESA
			,CONVERT (datetime, @FECHA_ENTREVISTA, 103) 
			,@CONTACTO
			,@ESTAMENTO
			,@CARGO
			,@TELEFONO
			,@CORREO
			,@COMENTARIO
			,@RUT_EJECUTIVO_INGRESO
			,SYSDATETIME()
			,@OFICINA_EJECUTIVO_INGRESO
			,@ANEXO
)
			
	--SELECT TOP 1 IdEntrevista FROM [CARTERAS].[TABCART_CABECERAENTREVISTA]
	--WHERE RutEmpresa = @RUT_EMPRESA
	--ORDER BY IdEntrevista DESC 
	SELECT SCOPE_IDENTITY() IdEntrevista
END