IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID('[dbo].[sp_Encuesta_01_InsertEncuesta]') AND type = 'P')
DROP PROCEDURE [dbo].[sp_Encuesta_01_InsertEncuesta]
GO
CREATE PROCEDURE [dbo].[sp_Encuesta_01_InsertEncuesta]  
@Rut_Afiliado varchar(12),  
@Nombre_Afiliado varchar(150),  
--@Fecha_Encuesta datetime,  
@Rut_Ejecutivo varchar(12),  
@Sucursal int,  
@Tiene_Enfermedad varchar(10),  
@Enfermedad_1 varchar(150),  
@Enfermedad_2 varchar(150),  
@Enfermedad_3 varchar(150),  
@Enfermedad_4 varchar(150),  
@Enfermedad_5 varchar(150),  
@Enfermedad_6 varchar(150),  
@Enfermedad_7 varchar(150),  
@Enfermedad_8 varchar(150),  
@Enfermedad_9 varchar(150),  
@Enfermedad_10 varchar(150),  
@Enfermedad_11 varchar(150),  
@Medicamentos_1 varchar(150),  
@Medicamentos_2 varchar(150),  
@Medicamentos_3 varchar(150),  
@Medicamentos_4 varchar(150),  
@Medicamentos_5 varchar(150),  
@Medicamentos_6 varchar(150),  
@Medicamentos_7 varchar(150),  
@Medicamentos_8 varchar(150),  
@Medicamentos_9 varchar(150),  
@Medicamentos_10 varchar(150),  
@Medicamentos_11 varchar(150),  
@Medicamentos_12 varchar(150),  
@Medicamentos_13 varchar(150),  
@Medicamentos_14 varchar(150),  
@Medicamentos_15 varchar(150),  
@Medicamentos_16 varchar(150),  
@Adquiere_Consultorio varchar(150),  
@Adquiere_CanastaGes varchar(150),  
@Adquiere_Farmacia varchar(150),  
@NombreFarmacia varchar(150),  
@Actividad varchar(150),  
@Sexo varchar(10),  
@Edad varchar(10),  
@Prevision varchar(30),  
@region varchar(150),   
@Flag_Encuesta int  
  
  
AS  
BEGIN  
  
insert into [BD_HERRAMIENTAS].[dbo].[TabEncuesta_01_PatologiaMedicamento]  
Select  
@Rut_Afiliado,  
@Nombre_Afiliado,  
GETDATE(),  
@Rut_Ejecutivo,  
@Sucursal,  
@Tiene_Enfermedad,  
@Enfermedad_1,  
@Enfermedad_2,  
@Enfermedad_3,  
@Enfermedad_4,  
@Enfermedad_5,  
@Enfermedad_6,  
@Enfermedad_7,  
@Enfermedad_8,  
@Enfermedad_9,  
@Enfermedad_10,  
@Enfermedad_11,  
@Medicamentos_1,  
@Medicamentos_2,  
@Medicamentos_3,  
@Medicamentos_4,  
@Medicamentos_5,  
@Medicamentos_6,  
@Medicamentos_7,  
@Medicamentos_8,  
@Medicamentos_9,  
@Medicamentos_10,  
@Medicamentos_11,  
@Medicamentos_12,  
@Medicamentos_13,  
@Medicamentos_14,  
@Medicamentos_15,  
@Medicamentos_16,  
@Adquiere_Consultorio,  
@Adquiere_CanastaGes,  
@Adquiere_Farmacia,  
@NombreFarmacia,  
@Actividad,  
@Sexo,  
@Edad,  
@Prevision,  
@Region,  
@Flag_Encuesta  
  
  
  
END